<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.orm.default_entity_manager' shared service.

include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/AnnotationDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/NamingStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/UnderscoreNamingStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/QuoteStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/RepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php';
include_once $this->targetDirs[3].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Configuration.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php';
include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/ObjectManager.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/EntityListenerResolver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Mapping/EntityListenerServiceResolver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Mapping/ContainerAwareEntityListenerResolver.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/ManagerConfigurator.php';

$a = new \Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain();
$a->addDriver(new \Doctrine\ORM\Mapping\Driver\AnnotationDriver(${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'}, $this->getParameter('api_platform.resource_class_directories')), 'App\\Entity');

$b = new \Doctrine\ORM\Configuration();
$b->setEntityNamespaces(array('App' => 'App\\Entity'));
$b->setMetadataCacheImpl(${($_ = isset($this->services['doctrine_cache.providers.doctrine.orm.default_metadata_cache']) ? $this->services['doctrine_cache.providers.doctrine.orm.default_metadata_cache'] : $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultMetadataCacheService.php')) && false ?: '_'});
$b->setQueryCacheImpl(${($_ = isset($this->services['doctrine_cache.providers.doctrine.orm.default_query_cache']) ? $this->services['doctrine_cache.providers.doctrine.orm.default_query_cache'] : $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultQueryCacheService.php')) && false ?: '_'});
$b->setResultCacheImpl(${($_ = isset($this->services['doctrine_cache.providers.doctrine.orm.default_result_cache']) ? $this->services['doctrine_cache.providers.doctrine.orm.default_result_cache'] : $this->load('getDoctrineCache_Providers_Doctrine_Orm_DefaultResultCacheService.php')) && false ?: '_'});
$b->setMetadataDriverImpl($a);
$b->setProxyDir(($this->targetDirs[0].'/doctrine/orm/Proxies'));
$b->setProxyNamespace('Proxies');
$b->setAutoGenerateProxyClasses(true);
$b->setClassMetadataFactoryName('Doctrine\\ORM\\Mapping\\ClassMetadataFactory');
$b->setDefaultRepositoryClassName('Doctrine\\ORM\\EntityRepository');
$b->setNamingStrategy(new \Doctrine\ORM\Mapping\UnderscoreNamingStrategy());
$b->setQuoteStrategy(new \Doctrine\ORM\Mapping\DefaultQuoteStrategy());
$b->setEntityListenerResolver(${($_ = isset($this->services['doctrine.orm.default_entity_listener_resolver']) ? $this->services['doctrine.orm.default_entity_listener_resolver'] : $this->services['doctrine.orm.default_entity_listener_resolver'] = new \Doctrine\Bundle\DoctrineBundle\Mapping\ContainerAwareEntityListenerResolver($this)) && false ?: '_'});
$b->setRepositoryFactory(new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Repository\\CensoMunicipioRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\CensoMunicipioRepository']) ? $this->services['App\Repository\CensoMunicipioRepository'] : $this->load('getCensoMunicipioRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\ColoniaRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\ColoniaRepository']) ? $this->services['App\Repository\ColoniaRepository'] : $this->load('getColoniaRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\ComunidadesRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\ComunidadesRepository']) ? $this->services['App\Repository\ComunidadesRepository'] : $this->load('getComunidadesRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\EmplazamientoRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\EmplazamientoRepository']) ? $this->services['App\Repository\EmplazamientoRepository'] : $this->load('getEmplazamientoRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\LocNidosColRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\LocNidosColRepository']) ? $this->services['App\Repository\LocNidosColRepository'] : $this->load('getLocNidosColRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\LocNidosNoColRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\LocNidosNoColRepository']) ? $this->services['App\Repository\LocNidosNoColRepository'] : $this->load('getLocNidosNoColRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\PoblacionesRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\PoblacionesRepository']) ? $this->services['App\Repository\PoblacionesRepository'] : $this->load('getPoblacionesRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\ProvinciasRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\ProvinciasRepository']) ? $this->services['App\Repository\ProvinciasRepository'] : $this->load('getProvinciasRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TerritorioRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TerritorioRepository']) ? $this->services['App\Repository\TerritorioRepository'] : $this->load('getTerritorioRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TipoEdificioRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TipoEdificioRepository']) ? $this->services['App\Repository\TipoEdificioRepository'] : $this->load('getTipoEdificioRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\TipoPropiedadRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\TipoPropiedadRepository']) ? $this->services['App\Repository\TipoPropiedadRepository'] : $this->load('getTipoPropiedadRepositoryService.php')) && false ?: '_'};
}, 'App\\Repository\\VisitasColoniaRepository' => function () {
    return ${($_ = isset($this->services['App\Repository\VisitasColoniaRepository']) ? $this->services['App\Repository\VisitasColoniaRepository'] : $this->load('getVisitasColoniaRepositoryService.php')) && false ?: '_'};
}))));

$this->services['doctrine.orm.default_entity_manager'] = $instance = \Doctrine\ORM\EntityManager::create(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->load('getDoctrine_Dbal_DefaultConnectionService.php')) && false ?: '_'}, $b);

${($_ = isset($this->services['doctrine.orm.default_manager_configurator']) ? $this->services['doctrine.orm.default_manager_configurator'] : $this->services['doctrine.orm.default_manager_configurator'] = new \Doctrine\Bundle\DoctrineBundle\ManagerConfigurator(array(), array())) && false ?: '_'}->configure($instance);

return $instance;
