<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGgv3pjt\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGgv3pjt/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGgv3pjt.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGgv3pjt\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGgv3pjt\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ggv3pjt',
    'container.build_id' => '41f13b5f',
    'container.build_time' => 1547659702,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGgv3pjt');
