<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyd1aqs\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyd1aqs/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSyd1aqs.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSyd1aqs\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSyd1aqs\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Syd1aqs',
    'container.build_id' => 'f18821a5',
    'container.build_time' => 1534327199,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyd1aqs');
